### ISSUE TITLE
README - Workshops 2: Installing pre-requisites lab link broken

### ISSUE THREAD

**Issue by timroster** [IBM/openshift-on-ibm-cloud-workshops#3]
Workshop 2 in the list of links, the link to pre-reqs:

`https://github.com/IBM/openshift-on-ibm-cloud-workshops/blob/master/documentation/1-prereqs.md`

returns a 404.

**Comment by thomassuedbroecker** [comment]
May thanks @timroster for all your feedback and that is even more than in that single issue. I forgot to merge your request. Sorry for that. But now it is fixed. Greetings Thomas
